/*jIskvFDoIP833FZBDAxST/eiSBJ01iAh/EoYkmD/mSZdMAkyxSLT0Gau8e3aPSXW*/

// 常量
export const  constant = {
	lpagecode: '36070WC_L01',
	searchcode: 'search_cashdraw_L01',
	ltablecode: 'table_cashdraw_L01',
	cpagecode: '36070WC_C01',
	innerId :'0001Z01000000000036R',
	ctablecode: 'table_cashdraw_C01',
	formcode1: 'form_cashdraw_C01',
	formcode2: 'form_cashdraw_C02',
	formcode3: 'form_cashdraw_C03',
	oid: '0001Z61000000000PASP',
	appregisterpk: '0001Z61000000001PA3B',
	appcode: "36070WC",
	// 审批pagecode
	approve_card_pagecode:'36070WCA_C01',

	advancesearch_list_pagecode:'36070WC_L03',

	mutiLangCode: '36070WC',
	module_name: 'cmp',
	module_id: '36070',
	module_tmpub_name:'tmpub',
	module_tmpub_id: '3601',

	billtype: '36S2',

	cardpath: '/card',
	listpath: '/list',
	cardlinkpath: '/cardlink',
	listlinkpath: '/listlink',

	// vo类路径
	voclasspath: 'nc.vo.cmp.cash.CashDrawVO',

	linksrc: 'cashdraw',

	printtemplateid: '1001Z61000000000F2HY',
	printfuncode: 'NCC36070WC',
	printnodekey: 'NCC36070WC',

	// 缓存datasource,缓存key
	cacheDataSource: 'cmp.cash.cashdraw.cacheDataSource',
	tobesubmittab: 'tobesubmittab_36070WC',
	approvingtab: 'approvingtab_36070WC',
	tobesettletab: 'tobesettletab_36070WC',
	conditionCache: 'conditionCache_36070WC',
	searchKey: 'searchKey_36070WC',
	custconditionCache: 'custconditionCache_36070WC',
	pageInfo: 'pageInfo_36070WC',
	tabInfo: 'tabInfo_36070WC',
	fipscene_key: 'fipscene__36070WC',

	pkname: 'pk_cashdraw',
  saga_gtxid: 'saga_gtxid'
};

// 请求URL--doaction
export const requesturl = {
	afteredit :'/nccloud/cmp/cash/cashdrawafteredit.do',
	gotocardcheck:'/nccloud/cmp/cash/cashdrawgotocardcheck.do',
	query:'/nccloud/cmp/cash/cashdrawquery.do',
	querytabnum: '/nccloud/cmp/cash/cashdrawquerytabnum.do',
	querybyids: '/nccloud/cmp/cash/cashdrawquerybyids.do',
	add: '/nccloud/cmp/cash/cashdrawadd.do',
	delete: '/nccloud/cmp/cash/cashdrawdelete.do',
	editpermission: '/nccloud/cmp/cash/cashdraweditpermission.do',
	commit: '/nccloud/cmp/cash/cashdrawcommit.do',
	uncommit: '/nccloud/cmp/cash/cashdrawuncommit.do',
	makebill:'/nccloud/cmp/cash/cashdrawmakebill.do',
	oclmoneyevent: '/nccloud/cmp/cash/cashdrawoclmoneyevent.do',
	print:'/nccloud/cmp/cash/cashdrawprint.do',
	querycard: '/nccloud/cmp/cash/cashdrawquerycard.do',
	settle: '/nccloud/cmp/cash/cashdrawsettle.do',
	unsettle: '/nccloud/cmp/cash/cashdrawunsettle.do',
	copy: '/nccloud/cmp/cash/cashdrawcopy.do',
	save: '/nccloud/cmp/cash/cashdrawinsert.do',
	savesubmit: '/nccloud/cmp/cash/cashdrawsavesubmit.do',
	commitcard: '/nccloud/cmp/cash/cashdrawcommitcard.do',
	uncommitcard: '/nccloud/cmp/cash/cashdrawuncommitcard.do',
	settlecard: '/nccloud/cmp/cash/cashdrawsettlecard.do',
	unsettlecard: '/nccloud/cmp/cash/cashdrawunsettlecard.do',
	orgchange: '/nccloud/cmp/cash/cashdraworgchange.do',
	currencychange:'/nccloud/cmp/cash/cashdrawcurrencychange.do',
	voucherlink: '/nccloud/cmp/cash/cashdrawvoucherlink.do',
	appregisterrrlquery: '/nccloud/cmp/cash/appregisterrrlquery.do'

};

const btn = {
	btngroup:'btngroup',
	addBtn:'addBtn',
	deleteBtn:'deleteBtn',
	copyBtn:'copyBtn',
	submitBtn:'submitBtn',
	submitgroup:'submitgroup',
	unsubmitBtn:'unsubmitBtn',
	settleBtn:'settleBtn',
	settlegroup:'settlegroup',
	unsettleBtn:'unsettleBtn',
	imgBtn:'imgBtn',
	imggroup:'imggroup',
	imgreviewBtn:'imgreviewBtn',
	imgscanBtn:'imgscanBtn',
	enclosureBtn:'enclosureBtn',
	joinquery:'joinquery',
	joinquerygroup:'joinquerygroup',
	cashbalanceBtn:'cashbalanceBtn',
	bankaccbalanceBtn:'bankaccbalanceBtn',
	voucherBtn:'voucherBtn',
	approveopinionBtn:'approveopinionBtn',
	printBtn:'printBtn',
	printgroup:'printgroup',
	outputBtn:'outputBtn',
	refreshBtn:'refreshBtn',
	submitinBtn:'submitinBtn',
	unsubmitinBtn:'unsubmitinBtn',
	deleteinBtn:'deleteinBtn',
	settleinBtn:'settleinBtn',
	unsettleinBtn:'unsettleinBtn',
	makebillBtn:'makebillBtn',
	editinBtn:'editinBtn',
	transfer: "transfer",
	canceltransfer:"canceltransfer"
  };
  
  export const button = {
	listdisable: [
	//   btn.btngroup,
	  btn.deleteBtn,
	  btn.copyBtn,
	  btn.submitBtn,
	  btn.submitgroup,
	  btn.unsubmitBtn,
	  btn.settleBtn,
	  btn.settlegroup,
		btn.unsettleBtn,
		btn.transfer,
		btn.canceltransfer,
	//   btn.joinquery,
	  btn.joinquerygroup,
	  btn.cashbalanceBtn,
	  btn.bankaccbalanceBtn,
	  btn.voucherBtn,
	  btn.approveopinionBtn,
	  //   btn.imgBtn,
	  btn.imggroup,
	  btn.imgreviewBtn,
	  btn.imgscanBtn,
	  btn.printBtn,
	  btn.printgroup,
	  btn.outputBtn,
	  btn.enclosureBtn
	],
  
	refreshdisable: [
	//   btn.btngroup,
	  btn.deleteBtn,
	  btn.copyBtn,
	  btn.submitBtn,
	  btn.submitgroup,
	  btn.unsubmitBtn,
	  btn.settleBtn,
	  btn.settlegroup,
	  btn.unsettleBtn,
	//   btn.joinquery,
	  btn.joinquerygroup,
	  btn.cashbalanceBtn,
	  btn.bankaccbalanceBtn,
	  btn.voucherBtn,
	  btn.approveopinionBtn,
	  //   btn.imgBtn,
	  btn.imggroup,
	  btn.imgscanBtn,
	  btn.imgreviewBtn,
	  btn.printBtn,
	  btn.printgroup,
	  btn.outputBtn,
	  btn.enclosureBtn,
	  btn.transfer,
	  btn.canceltransfer
	//   btn.refreshBtn
	],
  tempsavedisable: [
	  btn.btngroup,
	  // btn.deleteBtn,
	  btn.copyBtn,
	  // btn.submitBtn,
	//   btn.submitgroup,
	  btn.joinquery,
	  btn.joinquerygroup,
	  btn.imgBtn,
	  btn.cashbalanceBtn,
	  btn.bankaccbalanceBtn,
	  btn.imggroup,
	  btn.printBtn,
	  btn.imgreviewBtn,
	  btn.printgroup,
	  btn.outputBtn,
	  btn.imgscanBtn,
	  btn.enclosureBtn,
	  btn.refreshBtn
	],
	savedisable: [
	  btn.btngroup,
	  btn.deleteBtn,
	  btn.copyBtn,
	  btn.submitBtn,
	//   btn.submitgroup,
	  btn.joinquery,
	  btn.joinquerygroup,
	  btn.imgBtn,
	  btn.cashbalanceBtn,
	  btn.bankaccbalanceBtn,
	  btn.imggroup,
	  btn.printBtn,
	  btn.imgreviewBtn,
	  btn.printgroup,
	  btn.outputBtn,
	  btn.imgscanBtn,
	  btn.enclosureBtn,
	  btn.refreshBtn
	],
	tobapprovedisable: [
	  btn.btngroup,
	  btn.copyBtn,
	//   btn.submitBtn,
	  btn.unsubmitBtn,
	  btn.joinquery,
	  btn.joinquerygroup,
	  btn.approveopinionBtn,
	  btn.imgBtn,
	  btn.cashbalanceBtn,
	  btn.bankaccbalanceBtn,
	  btn.imggroup,
	  btn.printBtn,
	  btn.imgreviewBtn,
	  btn.printgroup,
	  btn.outputBtn,
	  btn.imgscanBtn,
	  btn.enclosureBtn,
	  btn.refreshBtn
	],
	tobesettledisable: [
	  btn.btngroup,
	  btn.copyBtn,
	  btn.unsubmitBtn,
	  btn.settleBtn,
	//   btn.settlegroup,
	  btn.joinquery,
	  btn.joinquerygroup,
	  btn.approveopinionBtn,
	  btn.imgBtn,
	  btn.cashbalanceBtn,
	  btn.bankaccbalanceBtn,
	  btn.imggroup,
	  btn.printBtn,
	  btn.imgreviewBtn,
	  btn.printgroup,
	  btn.outputBtn,
	  btn.imgscanBtn,
	  btn.enclosureBtn,
	  btn.refreshBtn
	],
	overdisable: [
	  btn.btngroup,
	  btn.copyBtn,
	//   btn.settleBtn,
	  btn.settlegroup,
	  btn.unsettleBtn,
	  btn.joinquery,
	  btn.joinquerygroup,
	  btn.imgBtn,
	  btn.cashbalanceBtn,
	  btn.bankaccbalanceBtn,
	  btn.voucherBtn,
	  btn.approveopinionBtn,
	  btn.imggroup,
	  btn.printBtn,
	  btn.imgreviewBtn,
	  btn.printgroup,
	  btn.outputBtn,
	  btn.imgscanBtn,
	  btn.enclosureBtn,
	  btn.refreshBtn
	]
  };

/*jIskvFDoIP833FZBDAxST/eiSBJ01iAh/EoYkmD/mSZdMAkyxSLT0Gau8e3aPSXW*/