/*lyAUtF6Xzl2U/q/YcnLKhWfY+ELUFheZGA7i67L/+v/NF0sRF1f+MMvw6Q3tBySb*/
[
    'addgroup',
    'addBtn',
    'editBtn',
    'deleteBtn',
    'copyBtn',
    'savegroup',
    'saveBtn',
    'saveaddBtn',
    'savesubmitBtn',
    'cancelBtn',
    'submitBtn',
    'unsubmitBtn',
    'settleBtn',
    'unsettleBtn',
    'makebillBtn',
    'imgBtn',
    'imggroup',
    'imgreviewBtn',
    'imgscanBtn',

    'joinquery',
    'joinquerygroup',
    'cashbalanceBtn',
    'bankaccbalanceBtn',
    'voucherBtn',
    'approveopinionBtn',
    'printBtn',
    'printgroup',
    'outputBtn',
    'enclosureBtn',
    'refreshBtn'
]

/*lyAUtF6Xzl2U/q/YcnLKhWfY+ELUFheZGA7i67L/+v/NF0sRF1f+MMvw6Q3tBySb*/