/*lyAUtF6Xzl2U/q/YcnLKhWfY+ELUFheZGA7i67L/+v/NF0sRF1f+MMvw6Q3tBySb*/
// 列表注册按钮编码
[
    'btngroup',
    'editBtn',
    'deleteBtn',
    'submit',
    'submitgroup',
    'submitBtn',
    'unsubmitBtn',
    'preparenetBtn',
    'moreBtn',
    'joinquery',
    'bankaccbalanceBtn',
    'linksettlementBtn',
    'printgroup',
    'printBtn',
    'previewBtn',
    'outputBtn',
    'enclosure',
    'enclosureBtn',
    'editinBtn',
    'deleteinBtn',
    'submitinBtn',
    'unsubmitinBtn'
]
// 卡片注册按钮编码
[
    'editgroup',
    'editBtn',
    'deleteBtn',
    'savegroup',
    'saveBtn',
    'savesubmitBtn',
    'submitBtn',
    'unsubmitBtn',
    'cancelBtn',
    'preparenetBtn',
    'moreBtn',
    'joinquery',
    'linksettlementBtn',
    'bankaccbalanceBtn',
    'printgroup',
    'printBtn',
    'previewBtn',
    'outputBtn',
    'enclosure',
    'enclosureBtn'
]

/*lyAUtF6Xzl2U/q/YcnLKhWfY+ELUFheZGA7i67L/+v/NF0sRF1f+MMvw6Q3tBySb*/