/*lyAUtF6Xzl2U/q/YcnLKhWfY+ELUFheZGA7i67L/+v/NF0sRF1f+MMvw6Q3tBySb*/
[
	'btngroup',
	'addBtn',
	'deleteBtn',
	'copyBtn',
	'submitBtn',
	'submitgroup',
	'unsubmitBtn',
	'settleBtn',
	'settlegroup',
	'unsettleBtn',
	'entrustBtn',
	'entrustgroup',
	'unentrustBtn',
	'paymentgroupBtn',
	'paymentgroup',
	'cyberbankeditBtn',
	'onlinepaymentBtn',
	'updatecyberbankBtn',
	'joinquery',
	'joinquerygroup',
	'querybillBtn',
	'voucherBtn',
	'inaccbalanceBtn',
	'outaccbalanceBtn',
	'netbankinfoBtn',
	'approveopinionBtn',
	'payconfirmBtn',
	'moreBtn',
	'print',
	'printBtn',
	'outputBtn',
	'img',
	'imgreviewBtn',
	'imgscanBtn',
	'subsidiary',
	'enclosureBtn',
	'redhandleBtn',
	'refreshBtn',
	'submitinBtn',
	'editinBtn',
	'deleteinBtn',
	'unsubmitinBtn',
	'settleinBtn',
	'unsettleinBtn',
	'makebillBtn',
	'entrustinBtn',
	'onlinepaymentinBtn',
	'unentrustinBtn'
];
JSON.stringify({
	billsta: record.busistatus.value,
	isinner: record.isinner_pay.value,
	balatypepk: record.pk_balatype.value,
	isnetbank: isnetbank,
	settlesatus: record.settlesatus.value,
	id: record.pk_transformbill.value
})
/*lyAUtF6Xzl2U/q/YcnLKhWfY+ELUFheZGA7i67L/+v/NF0sRF1f+MMvw6Q3tBySb*/