//pmFWCFu5nhKkBzYmrkBakbkX4wRw2WXUC8GpteVcynma5Q+e7oLMhX8cQgHQ3bwX
import { ajax, base } from 'nc-lightapp-front';
export default function (props) {


    let meta = {}
    const callback = (json, status, inlt) => {
        // if(!status) return ;
        meta = {
            button: [{

                children: [],
                area: "page_header",
                btncolor: "button_main",
                children: [],
                id: "1001Z0100000000072Q8",
                isenable: true,
                iskeyfunc: false,
                key: "add",
                keyboard: "ctrl+/",
                order: "1",
                parentCode: "page_group",
                title: "新增",
                type: "general_btn",
            },
            {

                children: [],
                area: "page_header",
                btncolor: "button_main",
                children: [],
                id: "1001Z0100000000072Q8",
                isenable: true,
                iskeyfunc: false,
                key: "page_save",
                keyboard: "ctrl+/",
                order: "1",
                parentCode: "page_group",
                title: "保存",
                type: "general_btn",
            },
            {

                children: [],
                area: "page_header",
                btncolor: "button_secondary",
                children: [],
                id: "1001Z0100000000072Q8",
                isenable: true,
                iskeyfunc: false,
                key: "page_cancel",
                keyboard: "ctrl+/",
                order: "1",
                parentCode: "page_group",
                title: "取消",
                type: "general_btn",
            },

            {

                children: [],
                area: "page_header",
                btncolor: "button_secondary",
                children: [],
                id: "1001Z0100000000072Q8",
                isenable: true,
                iskeyfunc: false,
                key: "version",
                keyboard: "ctrl+/",
                order: "1",
                parentCode: "page_group",
                title: "版本化",
                type: "general_btn",
            },


            {

                area: "page_header",
                btncolor: "button_secondary",
                children: [{
                    area: "page_header",
                    btncolor: "button_secondary",
                    children: [{
                        area: "page_header",
                        btncolor: "button_secondary",
                        children: [],
                        id: "1001Z010000000008M6Y",
                        isenable: true,
                        iskeyfunc: false,
                        key: "disable",
                        order: "7",
                        parentCode: "print_c",
                        title: "停用",
                        type: "general_btn"
                    }],
                    id: "1001Z010000000008M78",
                    isenable: true,
                    iskeyfunc: false,
                    key: "print_c",
                    order: "8",
                    parentCode: "print",
                    type: "general_btn"
                }],
                id: "1001Z010000000008J3Q",
                isenable: true,
                iskeyfunc: false,
                key: "Enable",
                order: "6",
                title: "启用",
                type: "divider"
            },
            {
                area: "page_header",
                btncolor: "button_secondary",
                children: [{
                    area: "page_header",
                    btncolor: "button_secondary",
                    children: [{
                        area: "page_header",
                        btncolor: "button_secondary",
                        children: [],
                        id: "1001Z010000000008M6Y",
                        isenable: true,
                        iskeyfunc: false,
                        key: "output",
                        order: "7",
                        parentCode: "print_c",
                        title: "输出",
                        type: "general_btn"
                    }],
                    id: "1001Z010000000008M78",
                    isenable: true,
                    iskeyfunc: false,
                    key: "print_c",
                    order: "8",
                    parentCode: "print",
                    type: "general_btn"
                }],
                id: "1001Z010000000008J3Q",
                isenable: true,
                iskeyfunc: false,
                key: "print",
                order: "6",
                title: "打印",
                type: "divider"
            },

            {

                children: [],
                area: "tab_header",
                btncolor: "button_secondary",
                children: [],
                id: "1001Z0100000000072Q8",
                isenable: true,
                iskeyfunc: false,
                key: "Import",
                keyboard: "ctrl+/",
                order: "1",
                parentCode: "page_group",
                title: "引入",
                type: "general_btn",
            }, {

                children: [],
                area: "tab_header",
                btncolor: "button_secondary",
                children: [],
                id: "1001Z0100000000072Q8",
                isenable: true,
                iskeyfunc: false,
                key: "del",
                keyboard: "ctrl+/",
                order: "1",
                parentCode: "page_group",
                title: "删除",
                type: "general_btn",
            },
            {
                id: "1002Z01000000000P5VJ", type: "buttongroup",
                key: "VEditGroup",
                area: "vers_head",
                iskeyfunc: false,
                btncolor: "button_secondary",
                isenable: true,
                order: "16",
                children: [{
                    id: "0001Z010000000SG3Z7L",
                    type: "general_btn",
                    key: "AddVersion",
                    title: "新增",
                    area: "vers_head",
                    keyboard: "ctrl+/",
                    btncolor: "button_main",
                    isenable: true,
                    order: "17",
                    parentCode: "VEditGroup",
                    children: []
                }, {
                    id: "0001Z010000000SG3Z7M",
                    type: "general_btn",
                    key: "EditVersion",
                    title: "修改",
                    area: "vers_head",
                    keyboard: "alt+p",
                    btncolor: "button_secondary",
                    isenable: true,
                    order: "18",
                    parentCode: "VEditGroup",
                    children: []
                }, {
                    id: "0001Z01000000SG03Z7P",
                    type: "general_btn",
                    key: "DelVersion",
                    title: "删除",
                    area: "vers_head",
                    keyboard: "ctrl+del",
                    btncolor: "button_secondary",
                    isenable: true,
                    order: "19",
                    parentCode: "VEditGroup",
                    children: [],

                }]
            }, {
                id: "0001Z010000000SG3Z7R",
                type: "general_btn",
                key: "RefreshV",
                area: "vers_head",
                btncolor: "button_secondary",
                isenable: true,
                order: "20",
                children: []
            },{
                area: "vers_head",
                btncolor: "button_secondary",
                children: [],
                id: "0001Z01000000000B63G",
                isenable: true,
                key: "CancelVersion",
                keyboard: "alt+q",
                order: "22",
                title: "取消",
                type: "general_btn",
             },{
                area: "vers_head",
                btncolor: "button_main",
                children: [],
                id: "0001Z01000000000B63E",
                isenable: true,
                key: "SaveVersion",
                keyboard: "ctrl+s",
                order: "21",
                title: "保存",
                type: "general_btn",
             }







            ],

            template: {
                code: "10570501",
                name: "利润中心结构",
                pageid: "1001Z010000000009ET5",
                validateFlag: false,
                ts: "2019-06-28 20:37:07",
                bcbd_header: {
                    areastatus: "browse",
                    items: [{
                        col: "6",
                        colnum: "1",
                        hyperlinkflag: false,
                        isnextrow: false,
                        leftspace: "0",
                        rightspace: "0",
                        rows: "0",
                        attrcode: "code",
                        color: "#111111",
                        containlower: false,
                        datatype: "204",
                        disabled: false,
                        editAfterFlag: false,
                        fieldDisplayed: "refname",
                        fieldValued: "refpk",
                        isDataPowerEnable: true,
                        isnotmeta: false,
                        isResLabel: false,
                        isrevise: false,
                        isShowUnit: false,
                        itemtype: "number",
                        label: "编码",
                        // maxlength: "200",
                        onlyLeafCanSelect: false,
                        position: "1",
                        required: false,
                        scale: "0",
                        visible: true,
                    }, {
                        col: "6",
                        colnum: "1",
                        hyperlinkflag: false,
                        isnextrow: false,
                        leftspace: "0",
                        rightspace: "0",
                        rows: "0",
                        attrcode: "name",
                        color: "#111111",
                        containlower: false,
                        datatype: "30",
                        disabled: false,
                        editAfterFlag: false,
                        fieldDisplayed: "refname",
                        fieldValued: "refpk",
                        isDataPowerEnable: true,
                        isnotmeta: false,
                        isResLabel: false,
                        isrevise: false,
                        isShowUnit: false,
                        itemtype: "textarea",
                        label: "名称",
                        maxlength: "200",
                        onlyLeafCanSelect: false,
                        position: "2",
                        required: false,
                        scale: "0",
                        visible: true,

                    }, {
                        col: "6",
                        colnum: "1",
                        hyperlinkflag: false,
                        isnextrow: false,
                        leftspace: "0",
                        rightspace: "0",
                        rows: "0",
                        attrcode: "memo",
                        color: "#111111",
                        containlower: false,
                        datatype: "30",
                        disabled: false,
                        editAfterFlag: false,
                        fieldDisplayed: "refname",
                        fieldValued: "refpk",
                        isDataPowerEnable: true,
                        isnotmeta: false,
                        isResLabel: false,
                        isrevise: false,
                        isShowUnit: false,
                        itemtype: "textarea",
                        label: "上级利润中心组",
                        maxlength: "200",
                        onlyLeafCanSelect: false,
                        position: "3",
                        required: false,
                        scale: "0",
                        visible: true,

                    }, {
                        col: "6",
                        colnum: "1",
                        hyperlinkflag: false,
                        isnextrow: false,
                        leftspace: "0",
                        rightspace: "0",
                        rows: "0",
                        attrcode: "complement",
                        color: "#111111",
                        containlower: false,
                        datatype: "30",
                        disabled: false,
                        editAfterFlag: false,
                        fieldDisplayed: "refname",
                        fieldValued: "refpk",
                        isDataPowerEnable: true,
                        isnotmeta: false,
                        isResLabel: false,
                        isrevise: false,
                        isShowUnit: false,
                        itemtype: "textarea",
                        label: "负责人",
                        maxlength: "200",
                        onlyLeafCanSelect: false,
                        position: "14",
                        required: false,
                        scale: "0",
                        visible: true,

                    }, {
                        col: "6",
                        colnum: "1",
                        hyperlinkflag: false,
                        isnextrow: false,
                        leftspace: "0",
                        rightspace: "0",
                        rows: "0",
                        attrcode: "enable",
                        color: "#111111",
                        containlower: false,
                        datatype: "30",
                        disabled: false,
                        editAfterFlag: false,
                        fieldDisplayed: "refname",
                        fieldValued: "refpk",
                        isDataPowerEnable: true,
                        isnotmeta: false,
                        isResLabel: false,
                        isrevise: false,
                        isShowUnit: false,
                        itemtype: "switch_browse",
                        
                        label: "启用状态",
                        maxlength: "200",
                        onlyLeafCanSelect: false,
                        position: "14",
                        required: false,
                        scale: "0",
                        visible: true,

                    },

                    ],
                    moduletype: "form",
                    relationcode: "bcbd_bottom",
                    code: "bcbd_header",
                    name: "条码规则定义",
                    oid: "1001Z010000000009ET6",
                    areaVisible: true,
                    isunfold: true,
                    isnotmeta: false
                },

                bcbd_body: {
                    items: [{
                        hyperlinkflag: false,
                        islock: false,
                        istotal: false,
                        width: "190px",
                        attrcode: "pk_barruleitem",
                        color: "#111111",
                        containlower: false,
                        datatype: "51",
                        disabled: false,
                        editAfterFlag: false,
                        fieldDisplayed: "refname",
                        fieldValued: "refpk",
                        isDataPowerEnable: true,
                        isnotmeta: false,
                        isResLabel: false,
                        isrevise: false,
                        isShowUnit: false,
                        itemtype: "input",
                        label: "利润中心编码",
                        maxlength: "20",
                        onlyLeafCanSelect: false,
                        position: "1",
                        required: false,
                        scale: "0",
                        visible: true,
                    }, {
                        hyperlinkflag: false,
                        islock: false,
                        istotal: false,
                        width: "190px",
                        attrcode: "profitname",
                        color: "#111111",
                        containlower: false,
                        datatype: "4",
                        disabled: true,
                        editAfterFlag: false,
                        fieldDisplayed: "refname",
                        fieldValued: "refpk",
                        initialvalue: { display: "1", value: "1" },
                        isDataPowerEnable: true,
                        isnotmeta: false,
                        isResLabel: false,
                        isrevise: false,
                        isShowUnit: false,
                        itemtype: "string",
                        label: "利润中心名称",
                        max: "2147483647",
                        maxlength: "20",
                        min: "-2147483648",
                        onlyLeafCanSelect: false,
                        position: "2",
                        required: false,
                        scale: "0",
                        visible: true,
                    }, {
                        hyperlinkflag: false,
                        islock: false,
                        istotal: false,
                        width: "180px",
                        attrcode: "enable",
                        color: "#111111",
                        containlower: false,
                        datatype: "4",
                        disabled: true,
                        editAfterFlag: false,
                        fieldDisplayed: "refname",
                        fieldValued: "refpk",
                        initialvalue: { display: "1", value: "1" },
                        isDataPowerEnable: true,
                        isnotmeta: false,
                        isResLabel: false,
                        isrevise: false,
                        isShowUnit: false,
                        itemtype: "boolean",
                        label: "启用",
                        max: "2147483647",
                        maxlength: "20",
                        min: "-2147483648",
                        onlyLeafCanSelect: false,
                        position: "2",
                        required: false,
                        scale: "0",
                        visible: true,
                    }, {
                        hyperlinkflag: false,
                        islock: false,
                        istotal: false,
                        width: "180px",
                        attrcode: "startdata",
                        color: "#111111",
                        containlower: false,
                        datatype: "4",
                        disabled: true,
                        editAfterFlag: false,
                        fieldDisplayed: "refname",
                        fieldValued: "refpk",
                        initialvalue: { display: "1", value: "1" },
                        isDataPowerEnable: true,
                        isnotmeta: false,
                        isResLabel: false,
                        isrevise: false,
                        isShowUnit: false,
                        itemtype: "data",
                        label: "生效日期",
                        max: "2147483647",
                        maxlength: "20",
                        min: "-2147483648",
                        onlyLeafCanSelect: false,
                        position: "2",
                        required: false,
                        scale: "0",
                        visible: true,
                    }, {
                        hyperlinkflag: false,
                        islock: false,
                        istotal: false,
                        width: "180px",
                        attrcode: "disabledata",
                        color: "#111111",
                        containlower: false,
                        datatype: "4",
                        disabled: true,
                        editAfterFlag: false,
                        fieldDisplayed: "refname",
                        fieldValued: "refpk",
                        initialvalue: { display: "1", value: "1" },
                        isDataPowerEnable: true,
                        isnotmeta: false,
                        isResLabel: false,
                        isrevise: false,
                        isShowUnit: false,
                        itemtype: "data",
                        label: "失效日期",
                        max: "2147483647",
                        maxlength: "20",
                        min: "-2147483648",
                        onlyLeafCanSelect: false,
                        position: "2",
                        required: false,
                        scale: "0",
                        visible: true,
                    }
                    ],
                    moduletype: "table",
                    pagination: false,
                    code: "bcbd_body",
                    name: "关联利润中心",
                    oid: "1001Z010000000009ETS",
                    areaVisible: true,
                    //isunfold|表单展开状态| `isunfold: false`
                    isunfold: true,
                    isnotmeta: false,
                    appcode: "10570BCRG",
                    pagecode: "1057050101",
                    templateCode: "10570501",
                    pageid: "1001Z010000000009ET5",
                },
                
                systemversion: {
                    items: [{
                        col: "6",
                        colnum: "1",
                        hyperlinkflag: false,
                        isnextrow: false,
                        leftspace: "0",
                        rightspace: "0",
                        rows: "0",
                        attrcode: "vno",
                        containlower: false,
                     
                        datatype: "1",
                        disabled: true,
                        editAfterFlag: false,
                        fieldDisplayed: "refcode",
                        fieldValued: "refpk",
                        isDataPowerEnable: true,
                        isnotmeta: false,
                        isResLabel: false,
                        isrevise: false,
                        isShowUnit: false,
                        
                        itemtype: "input",
                        label: "版本编号",
                        maxlength: "50",
                        onlyLeafCanSelect: false,
                        position: "17",
                        required: false,
                        scale: "0",
                        visible: true
                        
                    },
                    {
                            attrcode: "vname",
                            containlower: false,
                            datatype: "58",
                            disabled: false,
                            col: "6",
                        colnum: "1",
                        hyperlinkflag: false,
                        isnextrow: false,
                        leftspace: "0",
                        rightspace: "0",
                        rows: "0",
               
                        editAfterFlag: false,
                        fieldDisplayed: "refcode",
                        fieldValued: "refpk",
                        isDataPowerEnable: true,
                        isnotmeta: false,
                        isResLabel: false,
                        isrevise: false,
                        isShowUnit: false,
                        
                        itemtype: "input",
                        label: "版本名称",
                        maxlength: "50",
                        onlyLeafCanSelect: false,
                        position: "17",
                        required: false,
                        scale: "0",
                        visible: true
                     
                    },

                    {
                        attrcode: "vstartdate",
                        containlower: false,
                        datatype: "33",
                        disabled: false,
                        col: "6",
                        colnum: "1",
                        hyperlinkflag: false,
                        isnextrow: false,
                        leftspace: "0",
                        rightspace: "0",
                        rows: "0",
               
                        editAfterFlag: false,
                        fieldDisplayed: "refcode",
                        fieldValued: "refpk",
                        isDataPowerEnable: true,
                        isnotmeta: false,
                        isResLabel: false,
                        isrevise: false,
                        isShowUnit: false,
                        
                        itemtype: "datepicker",
                        label: "版本生效日期",
                        maxlength: "50",
                        onlyLeafCanSelect: false,
                        position: "17",
                        required: false,
                        scale: "0",
                        visible: true				
                                        
                    },{
                        attrcode: "venddate",
                        containlower: false,
                        datatype: "33",
                        disabled: true,
                        col: "6",
                        colnum: "1",
                        hyperlinkflag: false,
                        isnextrow: false,
                        leftspace: "0",
                        rightspace: "0",
                        rows: "0",
               
                        editAfterFlag: false,
                        fieldDisplayed: "refcode",
                        fieldValued: "refpk",
                        isDataPowerEnable: true,
                        isnotmeta: false,
                        isResLabel: false,
                        isrevise: false,
                        isShowUnit: false,
                        
                        itemtype: "datepicker",
                        label: "版本失效日期",
                        maxlength: "50",
                        onlyLeafCanSelect: false,
                        position: "17",
                        required: false,
                        scale: "0",
                        visible: true
                    }
                ],
                    moduletype: "table",
                    pagination: false,
                    code: "vers",
                    // name: "报表合并体系版本信息",
                    // oid: "0001Z010000000005L78",
                    areaVisible: true,
                    isunfold: false,
                    // isnotmeta: false,
                    // appcode: "10100RCSG",
                    // pagecode: "10100RCSG_list",
                    // templateCode: "10100RCSG_list",
                    // pageid: "0001Z010000000005L55"
                    
                },


               
                gridrelation: { bcbd_body: { srcAreaCode: "bcbd_body", tabRelation: ["bcbd_body"] }, vers: { srcAreaCode: "vers", tabRelation: ["vers"] }},

                // formrelation: {bcbd_header:["bcbd_bottom"]},

                containerrelation: { bcbd_body: { layout: "vertical", tabs: [["bcbd_body"]] },vers: { layout: "vertical", tabs: [["vers"]] } },

            },




           
           


        }
        props.button.setButtons(meta.button);
        props.button.setButtonVisible({ 'page_save': false, 'page_cancel': false });
        // props.template.settemplate(meta.template);
        meta = meta.template
        props.meta.setMeta(meta);
    }
    props.MultiInit.getMultiLang({ 'moduleId': '1057-1057baor', 'domainName': 'uap', callback });
    // function (data) {
    //     if (data) {
    //         if (data.button) {
    //             let button = data.button;
    //             props.button.setButtons(button);
    //         }
    //         if (data.template) {
    //             let meta = data.template;
    //             props.meta.setMeta(meta);
    //         }
    //     }
    // }

}
//pmFWCFu5nhKkBzYmrkBakbkX4wRw2WXUC8GpteVcynma5Q+e7oLMhX8cQgHQ3bwX